import { dehydrate, HydrationBoundary } from "@tanstack/react-query";
import { Outfit, Noto_Serif_KR } from "next/font/google";

import "./globals.css";
import localFont from "next/font/local";

import Providers from "./providers";
import { GlobalHeader } from "@/components/global-header";
import { Toaster } from "@/components/ui/sonner";
import { getQueryClient } from "@/hooks/getQueryClient";
import { favoriteQueryOptions } from "@/lib/queries/favorite.query";
import { cn } from "@/lib/utils";

import type { Metadata } from "next";

const pretendard = localFont({
  src: "./PretendardVariable.woff2",
  variable: "--font-pretendard",
});

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-outfit",
});

const notoSerifKR = Noto_Serif_KR({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-noto-serif-kr",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = getQueryClient();

  await queryClient.prefetchQuery(favoriteQueryOptions());

  return (
    <html
      lang="ko"
      className={cn(
        "h-full",
        "antialiased",
        pretendard.variable,
        outfit.variable,
        notoSerifKR.variable,
      )}
    >
      <body className="flex min-h-full flex-col">
        <Providers>
          <HydrationBoundary state={dehydrate(queryClient)}>
            <GlobalHeader />
            {children}
            <Toaster />
          </HydrationBoundary>
        </Providers>
      </body>
    </html>
  );
}
