import { Outfit } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import z from "zod";
import { ko } from "zod/locales";

import Providers from "./providers";
import { GlobalHeader } from "@/components/global-header";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";

import type { Metadata } from "next";

z.config(ko());

const pretendard = localFont({
  src: "./PretendardVariable.woff2",
  variable: "--font-pretendard",
});

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={cn("h-full", "antialiased", pretendard.variable, outfit.variable)}>
      <body className="flex min-h-full flex-col">
        <Providers>
          <GlobalHeader />
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
